-- Website banner tables.
--
-- Website creatives use different dimensions than the app ones, so each
-- website screen gets its own table + storage bucket, mirroring the
-- existing app banner tables (homeherooffers, dineinhomebanners,
-- storeshomebanners, wellnesshomebanners, touristhomebanners) rather than
-- sharing rows with them. Column shape (names, order, nullability, defaults)
-- matches those tables exactly, verified against the live schema via
-- information_schema.columns, so the existing admin UI
-- (app/dashboard/offers) works against them unmodified.
--
-- Assumes public.set_updated_at() already exists (it is reused, not
-- redefined, by sql/service-categories.sql in this repo).

create table if not exists public.websitehomebanners (
  id bigint generated by default as identity primary key,
  title text null,
  type text not null,
  media_url text not null,
  thumbnail_url text null,
  cta_text text null,
  cta_link text null,
  priority integer null default 1,
  is_active boolean null default true,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  action jsonb null
) tablespace pg_default;

create table if not exists public.websitedineinbanners (
  id bigint generated by default as identity primary key,
  title text null,
  type text not null,
  media_url text not null,
  thumbnail_url text null,
  cta_text text null,
  cta_link text null,
  priority integer null default 1,
  is_active boolean null default true,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  action jsonb null
) tablespace pg_default;

create table if not exists public.websitestorebanners (
  id bigint generated by default as identity primary key,
  title text null,
  type text not null,
  media_url text not null,
  thumbnail_url text null,
  cta_text text null,
  cta_link text null,
  priority integer null default 1,
  is_active boolean null default true,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  action jsonb null
) tablespace pg_default;

create table if not exists public.websitewellnessbanners (
  id bigint generated by default as identity primary key,
  title text null,
  type text not null,
  media_url text not null,
  thumbnail_url text null,
  cta_text text null,
  cta_link text null,
  priority integer null default 1,
  is_active boolean null default true,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  action jsonb null
) tablespace pg_default;

create table if not exists public.websitetouristbanners (
  id bigint generated by default as identity primary key,
  title text null,
  type text not null,
  media_url text not null,
  thumbnail_url text null,
  cta_text text null,
  cta_link text null,
  priority integer null default 1,
  is_active boolean null default true,
  start_at timestamp with time zone null,
  end_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  action jsonb null
) tablespace pg_default;

-- Indexes: mirror the "active + priority" listing order the admin UI queries.
create index if not exists websitehomebanners_active_priority_idx on public.websitehomebanners using btree (is_active, priority);
create index if not exists websitedineinbanners_active_priority_idx on public.websitedineinbanners using btree (is_active, priority);
create index if not exists websitestorebanners_active_priority_idx on public.websitestorebanners using btree (is_active, priority);
create index if not exists websitewellnessbanners_active_priority_idx on public.websitewellnessbanners using btree (is_active, priority);
create index if not exists websitetouristbanners_active_priority_idx on public.websitetouristbanners using btree (is_active, priority);

-- Keep updated_at current on every row update.
drop trigger if exists trg_websitehomebanners_set_updated_at on public.websitehomebanners;
create trigger trg_websitehomebanners_set_updated_at before update on public.websitehomebanners for each row execute function set_updated_at ();

drop trigger if exists trg_websitedineinbanners_set_updated_at on public.websitedineinbanners;
create trigger trg_websitedineinbanners_set_updated_at before update on public.websitedineinbanners for each row execute function set_updated_at ();

drop trigger if exists trg_websitestorebanners_set_updated_at on public.websitestorebanners;
create trigger trg_websitestorebanners_set_updated_at before update on public.websitestorebanners for each row execute function set_updated_at ();

drop trigger if exists trg_websitewellnessbanners_set_updated_at on public.websitewellnessbanners;
create trigger trg_websitewellnessbanners_set_updated_at before update on public.websitewellnessbanners for each row execute function set_updated_at ();

drop trigger if exists trg_websitetouristbanners_set_updated_at on public.websitetouristbanners;
create trigger trg_websitetouristbanners_set_updated_at before update on public.websitetouristbanners for each row execute function set_updated_at ();

-- Row level security: public can read active banners, only admin/superadmin can write.
-- (Matches the policy shape in sql/service-categories.sql.)
alter table public.websitehomebanners enable row level security;
alter table public.websitedineinbanners enable row level security;
alter table public.websitestorebanners enable row level security;
alter table public.websitewellnessbanners enable row level security;
alter table public.websitetouristbanners enable row level security;

drop policy if exists websitehomebanners_public_read on public.websitehomebanners;
create policy websitehomebanners_public_read on public.websitehomebanners for select using (is_active = true);
drop policy if exists websitehomebanners_admin_write on public.websitehomebanners;
create policy websitehomebanners_admin_write on public.websitehomebanners for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitedineinbanners_public_read on public.websitedineinbanners;
create policy websitedineinbanners_public_read on public.websitedineinbanners for select using (is_active = true);
drop policy if exists websitedineinbanners_admin_write on public.websitedineinbanners;
create policy websitedineinbanners_admin_write on public.websitedineinbanners for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitestorebanners_public_read on public.websitestorebanners;
create policy websitestorebanners_public_read on public.websitestorebanners for select using (is_active = true);
drop policy if exists websitestorebanners_admin_write on public.websitestorebanners;
create policy websitestorebanners_admin_write on public.websitestorebanners for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitewellnessbanners_public_read on public.websitewellnessbanners;
create policy websitewellnessbanners_public_read on public.websitewellnessbanners for select using (is_active = true);
drop policy if exists websitewellnessbanners_admin_write on public.websitewellnessbanners;
create policy websitewellnessbanners_admin_write on public.websitewellnessbanners for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitetouristbanners_public_read on public.websitetouristbanners;
create policy websitetouristbanners_public_read on public.websitetouristbanners for select using (is_active = true);
drop policy if exists websitetouristbanners_admin_write on public.websitetouristbanners;
create policy websitetouristbanners_admin_write on public.websitetouristbanners for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

comment on table public.websitehomebanners is 'Home page banners for the public website (separate creatives/dimensions from the app).';
comment on table public.websitedineinbanners is 'Dine-in section banners for the public website.';
comment on table public.websitestorebanners is 'Store section banners for the public website.';
comment on table public.websitewellnessbanners is 'Wellness section banners for the public website.';
comment on table public.websitetouristbanners is 'Explore/tourist section banners for the public website.';

-- Storage buckets: one public bucket per website banner table, matching the
-- app banner buckets (HomeHeroOffers, DineinHomeBanners, StoresHomeBanners,
-- WellnessHomeBanners, TouristHomeBanners). Create via SQL or via the
-- Supabase dashboard (Storage > New bucket > Public bucket) — either works.
insert into storage.buckets (id, name, public)
values
  ('WebsiteHomeBanners', 'WebsiteHomeBanners', true),
  ('WebsiteDineinBanners', 'WebsiteDineinBanners', true),
  ('WebsiteStoreBanners', 'WebsiteStoreBanners', true),
  ('WebsiteWellnessBanners', 'WebsiteWellnessBanners', true),
  ('WebsiteTouristBanners', 'WebsiteTouristBanners', true)
on conflict (id) do nothing;

-- storage.objects RLS: a bucket's "public" flag only affects anonymous reads
-- via the public URL — every upload/replace/delete still goes through the
-- authenticated storage API and is subject to RLS on storage.objects, so
-- each bucket needs its own read/write policies here (same admin/superadmin
-- check used on the tables above).
drop policy if exists websitehomebanners_storage_read on storage.objects;
create policy websitehomebanners_storage_read on storage.objects for select
  using (bucket_id = 'WebsiteHomeBanners');
drop policy if exists websitehomebanners_storage_admin_write on storage.objects;
create policy websitehomebanners_storage_admin_write on storage.objects for insert to authenticated
  with check (bucket_id = 'WebsiteHomeBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitehomebanners_storage_admin_update on storage.objects;
create policy websitehomebanners_storage_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'WebsiteHomeBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (bucket_id = 'WebsiteHomeBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitehomebanners_storage_admin_delete on storage.objects;
create policy websitehomebanners_storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'WebsiteHomeBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitedineinbanners_storage_read on storage.objects;
create policy websitedineinbanners_storage_read on storage.objects for select
  using (bucket_id = 'WebsiteDineinBanners');
drop policy if exists websitedineinbanners_storage_admin_write on storage.objects;
create policy websitedineinbanners_storage_admin_write on storage.objects for insert to authenticated
  with check (bucket_id = 'WebsiteDineinBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitedineinbanners_storage_admin_update on storage.objects;
create policy websitedineinbanners_storage_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'WebsiteDineinBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (bucket_id = 'WebsiteDineinBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitedineinbanners_storage_admin_delete on storage.objects;
create policy websitedineinbanners_storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'WebsiteDineinBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitestorebanners_storage_read on storage.objects;
create policy websitestorebanners_storage_read on storage.objects for select
  using (bucket_id = 'WebsiteStoreBanners');
drop policy if exists websitestorebanners_storage_admin_write on storage.objects;
create policy websitestorebanners_storage_admin_write on storage.objects for insert to authenticated
  with check (bucket_id = 'WebsiteStoreBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitestorebanners_storage_admin_update on storage.objects;
create policy websitestorebanners_storage_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'WebsiteStoreBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (bucket_id = 'WebsiteStoreBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitestorebanners_storage_admin_delete on storage.objects;
create policy websitestorebanners_storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'WebsiteStoreBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitewellnessbanners_storage_read on storage.objects;
create policy websitewellnessbanners_storage_read on storage.objects for select
  using (bucket_id = 'WebsiteWellnessBanners');
drop policy if exists websitewellnessbanners_storage_admin_write on storage.objects;
create policy websitewellnessbanners_storage_admin_write on storage.objects for insert to authenticated
  with check (bucket_id = 'WebsiteWellnessBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitewellnessbanners_storage_admin_update on storage.objects;
create policy websitewellnessbanners_storage_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'WebsiteWellnessBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (bucket_id = 'WebsiteWellnessBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitewellnessbanners_storage_admin_delete on storage.objects;
create policy websitewellnessbanners_storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'WebsiteWellnessBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));

drop policy if exists websitetouristbanners_storage_read on storage.objects;
create policy websitetouristbanners_storage_read on storage.objects for select
  using (bucket_id = 'WebsiteTouristBanners');
drop policy if exists websitetouristbanners_storage_admin_write on storage.objects;
create policy websitetouristbanners_storage_admin_write on storage.objects for insert to authenticated
  with check (bucket_id = 'WebsiteTouristBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitetouristbanners_storage_admin_update on storage.objects;
create policy websitetouristbanners_storage_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'WebsiteTouristBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')))
  with check (bucket_id = 'WebsiteTouristBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
drop policy if exists websitetouristbanners_storage_admin_delete on storage.objects;
create policy websitetouristbanners_storage_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'WebsiteTouristBanners' and exists (select 1 from public.users u where u.id = auth.uid() and lower(coalesce(u.role, '')) in ('admin', 'superadmin')));
